services:
  prism-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blood-group-prediction
    ports:
      - "8501:8501"
    volumes:
      - ./model.pth:/app/model.pth:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
